name: draft_selection
description: Select best draft read for polishing using fastANI all-vs-all comparison
keywords:
  - draft
  - selection
  - fastani
  - ani
  - consensus
tools:
  - fastani:
      description: Fast whole-genome similarity (ANI) estimation
      homepage: https://github.com/ParBLiSS/FastANI
      documentation: https://github.com/ParBLiSS/FastANI/blob/master/README.md
      tool_dev_url: https://github.com/ParBLiSS/FastANI
      doi: "10.1038/s41467-018-07641-9"
      licence: ["Apache-2.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample_001', cluster_id:'5', single_end:true ]
  - corrected_reads:
      type: file
      description: Corrected reads in FASTA format from CANU_CORRECT
      pattern: "*.{fasta,fa,fasta.gz,fa.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - draft:
      type: file
      description: Selected draft read for polishing
      pattern: "*_draft.fasta"
  - ani_results:
      type: file
      description: All-vs-all ANI comparison results
      pattern: "*.ani.tsv"
  - stats:
      type: file
      description: Statistics about draft selection (JSON format)
      pattern: "*.selection.json"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@nanoclust-developers"
maintainers:
  - "@nanoclust-developers"
