name: fastani_classify
description: Taxonomic classification using Average Nucleotide Identity (ANI)
keywords:
  - classification
  - ANI
  - taxonomy
  - nanopore
tools:
  - fastani:
      description: Fast alignment-free computation of whole-genome Average Nucleotide Identity
      homepage: https://github.com/ParBLiSS/FastANI
      documentation: https://github.com/ParBLiSS/FastANI/blob/master/README.md
      tool_dev_url: https://github.com/ParBLiSS/FastANI
      doi: "10.1038/s41467-018-07641-9"
      licence: ["Apache-2.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample_001', cluster_id:'5', single_end:true ]
  - query:
      type: file
      description: Query consensus sequence in FASTA format
      pattern: "*.{fasta,fa,fna}"
  - reference_genomes:
      type: directory
      description: |
        Directory containing reference genomes or path to file listing reference paths
        Each reference should be a FASTA file (.fasta, .fa, or .fna)

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - results:
      type: file
      description: |
        FastANI results (tab-delimited)
        Format: query reference ANI fragments_aligned total_fragments
      pattern: "*.ani.txt"
  - stats:
      type: file
      description: Statistics about ANI classification (JSON format)
      pattern: "*.stats.json"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@nanoclust-developers"
maintainers:
  - "@nanoclust-developers"
