name: Feature request
description: Suggest an idea for NanoPulse
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for NanoPulse!

  - type: textarea
    id: description
    attributes:
      label: Description of feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Describe the use case for this feature. Why would this be useful?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered any alternative solutions or workarounds?
