name: canu_correct
description: Correct long nanopore reads using Canu's correction algorithm
keywords:
  - correction
  - nanopore
  - long-reads
  - canu
  - assembly
tools:
  - canu:
      description: Canu is a fork of the Celera Assembler designed for high-noise single-molecule sequencing
      homepage: https://canu.readthedocs.io/
      documentation: https://canu.readthedocs.io/en/latest/
      tool_dev_url: https://github.com/marbl/canu
      doi: "10.1101/gr.215087.116"
      licence: ["GPL v2"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample_001', cluster_id:'5', single_end:true ]
  - reads:
      type: file
      description: Input FASTQ file with nanopore reads for a single cluster
      pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
  - genome_size:
      type: string
      description: Expected genome/amplicon size (e.g., "1.5k" for 16S, "1.8k" for 18S)
  - polishing_reads:
      type: integer
      description: Number of reads to use for correction (default 100)

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - corrected:
      type: file
      description: Corrected reads in FASTA format (optional - may fail for small clusters)
      pattern: "*.correctedReads.fasta"
  - stats:
      type: file
      description: Statistics about the correction process (JSON format)
      pattern: "*.stats.json"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@nanoclust-developers"
maintainers:
  - "@nanoclust-developers"
